version: 0.0
os: ubuntu
files:
  - source: /
    destination: /root/dj-localgovai-backend/
hooks:
  BeforeInstall:
      - location: scripts/before_install.sh
  AfterInstall:
      - location: scripts/after_install.sh